### ISSUE TITLE
Removal request

### ISSUE THREAD

**Issue by arctic5** [Gang-Garrison-2/gg2plugins#1] opened 2015-07-03 05:56 UTC
Requesting for the following plugins to be ---->_removed_<---:
ssb
chat_ext
walljump

**Comment by hikari-no-yume** [comment] 2015-07-03 12:11
I'm not removing old versions.

**Comment by wareya** [comment] 2015-07-03 12:38
Update them with dummy plugins. You're distributing broken code. That way people running old versions can just use the md5 selector to use the appropriate version, without letting server owners accidentally run broken code.

**Comment by hikari-no-yume** [comment] 2015-07-03 13:14
I don't agree with that either. We shouldn't ship fake plugins.

The code is not broken, it just does not work with the current version of GG2. A better way to resolve this is to add GG2 version information.

**Comment by wareya** [comment] 2015-07-03 13:15
If you don't fix it the right way, fix it the wrong way. I don't care. It doesn't matter.

**Comment by Medo42** [comment] 2015-07-03 14:32
I'm generally with ajf on this one, but it would be some effort to keep track of version compatibility.

**Comment by hikari-no-yume** [comment] 2015-07-03 15:07
Fixing it server-side is a horrible hack and means you need to use obtuse workarounds to load plugins on old GG2 versions.

What I should do is make GG2 check if plugins are compatible before letting you host with them. That might be a challenge, though.

Argh, this is a tough problem to solve :/

**Comment by hikari-no-yume** [comment] 2015-07-03 15:09
Part of the problem is we don't actually know which plugins are and aren't compatible, or at least not in any fine-grained way: we can't say "this last worked on version 2.X.X", we just know it doesn't work on the current one. That's messy. We also don't know which specific versions of a plugin don't work.

Now that I think about this, isn't it a non-issue anyway? Servers execute server-sent plugins, it's not just the clients. If the plugin really is horribly broken on the latest version, surely the server will crash before the clients do? If the server doesn't crash then, well, presumably the plugin is broken but harmless.

**Comment by arctic5** [comment] 2015-07-03 16:34
you exclude the possibility of crashes happening midgame

**Comment by wareya** [comment] 2015-07-03 16:43
there _are_ cases where the server wouldn't crash, e.g. client-only code

**Comment by arctic5** [comment] 2015-07-03 16:45
also chatext and chat are prone to erroring caused by other clients

**Comment by hikari-no-yume** [comment] 2015-07-03 17:32
This is true. But I'd rather not mess up the plugins source. Arctic, you can put a big message on your plugin topic saying "don't use this, crashes on 2.8" if you want to.

**Comment by wareya** [comment] 2015-07-03 17:45
I would rather have a solution that actually works.

**Comment by Medo42** [comment] 2015-07-03 19:46
@arctic5 told me on steam that he just wants the plugins removed and they are his plugins so there.

> arctismo: i just want them removed cos i wont them removed
> arctismo: that other thing was just extra frosting

I don't think we ever specified any particular license terms for plugins, so if he wants the plugins gone we should probably remove them even if we might not have to. I'm reopening the issue for that purpose.

This leaves us to discuss how we want to solve this kind of issue in the future, and whether we want to specify some explicit terms for having your plugins on our server, e.g. that we can keep them there indefinitely.

**Comment by hikari-no-yume** [comment] 2015-07-03 19:56
Yeah, that's been something I was thinking about. We need some sort of license. Maybe something like:

> By requesting that we add your plugin to the Gang Garrison 2 plugin repository, you
> 1. grant us, the Gang Garrison 2 plugin repository maintainers, the right to distribute your server-sent plugin from the repository (or its successors) forever;
> 2. certify that the plugin is not malicious and accept that we will not be held liable if it is;
> 3. certify that the plugin is legal under US and German law;
> 4. certify that you have the right to submit the plugin to us and are not infringing any applicable copyrights, trademarks, or other intellectual property.

I could remove the plugin from the repo, that would stop people using it. It'd still be in the git history though.

**Comment by Medo42** [comment] 2015-07-03 20:36
I guess that is all arctic wants here, but he'd have to say that himself. Why he has to tell this stuff to me on steam instead of just writing it here is beyond me.

**Comment by wareya** [comment] 2015-07-03 20:37
Because if he just wrote it here AJF would shut him down and not take him seriously

**Comment by Medo42** [comment] 2015-07-03 20:39
Ah, but you see, I'm also reading what is written here so I can shut down AJF in return :)

**Comment by wareya** [comment] 2015-07-03 20:40
Nice

**Comment by hikari-no-yume** [comment] 2015-07-03 21:01
Well, I went and simply removed them, though I made them still be in the plugin list, albeit marked as deleted (I don't like how arctic's tried to erase their existence).

If people _really_ want these plugins, they can always download them from the git repo, I guess.

**Comment by arctic5** [comment] 2015-07-04 00:38
tyvm

**Comment by arctic5** [comment] 2015-07-06 09:14
lorgan pointed it out and i forgot but, when i said "removed" i wanted it out of sight out of mind, not front and center at the top of the list, please fix it.

**Comment by wareya** [comment] 2015-07-06 13:06
lol

**Comment by hikari-no-yume** [comment] 2015-07-06 14:05
lol

**Comment by wareya** [comment] 2015-07-06 14:05
no

**Comment by hikari-no-yume** [comment] 2015-07-06 14:07
If a plugin someone's using suddenly vanishes, it should at least be obvious it's removed. The sort order happens to put the removed ones at the top, but that's coincidence.

**Comment by wareya** [comment] 2015-07-06 14:37
Then fix the sort order. "Coincidence" doesn't justify a blatant bug.

**Comment by TazeTSchnitzel** [comment] 2015-07-06 14:42
I think I've come up with a (hacky) workaround that would "fix" this. One moment.

**Comment by hikari-no-yume** [comment] 2015-07-06 15:09
Refactoring this would be a pain. I may do it later.

**Comment by wareya** [comment] 2015-07-06 15:11
You could write a temporary filter until you figure out how to do it right. Just don't display deleted plugins for now. No big deal.

**Comment by arctic5** [comment] 2015-07-07 07:11
Here let me fill you in on 2 simpler solutions,

**Comment by arctic5** [comment] 2015-07-07 07:20
Here let me fill you in on two simpler solutions:
a: delete the files, delete the entries
b: revert 3 git commits

I believe whats going on here you're trying to think outside of the box when really the solution is right in front of y'all

**Comment by hikari-no-yume** [comment] 2015-07-07 10:48
I'm not hiding that the plugins were deleted. If plugins are removed, it should at least be obvious.

**Closed as completed** 2017-05-05 23:10 UTC

**Comment by hikari-no-yume** [comment] 2017-05-05 23:14
Fixed the sort order thing with a horrible code kludge (the removed plugins were at the top of the list by accident, because the sorting is actually based on the HTML, so I checked for `<del>` in the sorting code… ugh.) Sorry for having been an arsehole about this two years back. I don't like being mean to people.
